name: Animatorials
favicon: null
layout_spectrum: 0.35051
typography_spectrum: 0.61465
title: Editorials Written By Animals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#918881'
    - '#162021'
    - '#8db342'
    - '#465819'
    - '#c3e5fd'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
