name: Animatorials
favicon: null
layout_spectrum: 0.24437
typography_spectrum: 0.6807441806886345
title: Animaltorials - Editorials Written By Animals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#182213'
    - '#796836'
    - '#d1ae7a'
    - '#d4774b'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.9612908123526722
  rhythmicContrast: 0.23737342609092593
purpose: []
