name: Animatorials
favicon: null
layout_spectrum: 0.18877
typography_spectrum: 0.61465
title: Editorials Written By Animals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#182213'
    - '#796836'
    - '#d1ae7a'
    - '#d4774b'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
